### ISSUE TITLE
Update LABTASKS and README to reflect any upgrades

### ISSUE THREAD

**Issue by kklamberty** [UMM-CSci-3601/3601-lab4-mongo-2020#1]
In particular, we probably want to link to more recent documentation for the Angular stuff in the lab.

**Comment by floogulinc** [comment]
We should add some stuff about the Azure Cosmos DB extension that is now recommended. Here are some screenshots we can use:

| https://i.vgy.me/AWAUHw.png ![](https://i.vgy.me/AWAUHw.png) | https://i.vgy.me/ElqdfW.png ![]( https://i.vgy.me/ElqdfW.png) | https://i.vgy.me/2dk1ws.png ![](https://i.vgy.me/2dk1ws.png) |
|---|---|---|
